# Generated by Django 4.1.5 on 2023-02-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrenda', models.CharField(max_length=100)),
                ('masculino', models.CharField(max_length=100)),
                ('femenino', models.CharField(max_length=100)),
                ('talle', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrenda', models.CharField(max_length=100)),
                ('nena', models.CharField(max_length=100)),
                ('varon', models.CharField(max_length=100)),
                ('talle', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrenda', models.CharField(max_length=100)),
                ('verano', models.CharField(max_length=100)),
                ('invierno', models.CharField(max_length=100)),
                ('talle', models.IntegerField(max_length=100)),
            ],
        ),
    ]
